@startuml
"Пользователь" as user
user -down-> (Аутентифицироваться)
user -down-> (Войти без аккаунта)
(Аутентифицироваться) -up.> (Авторизоваться)
(Аутентифицироваться) -.> (Зарегистрироваться)
@enduml