@startuml
"Авторизованный\nпользователь" as user
user -left-> (Создать\nблокировку входа)
user -right-> (Разблокировать\nприложение)
(Создать\nблокировку входа) -down.> (Создать\nпин-код) : include
(Включить вход\nпри помощи\nотпечатка пальца) -down.> (Создать\nблокировку входа) : extend

(Разблокировать\nприложение) -down.> (Ввести\nпин-код) : include
(Использовать\nотпечаток пальца) -down.> (Разблокировать\nприложение) : extend
@enduml