@startuml
"Авторизованный\nпользователь" as user
user --> (Посмотреть подробную\nинформацию о посте)
user -up-> (Найти посты\nпо названию)
user -up-> (Обновить\nсписок постов)
user -up-> (Посмотреть\nсписок постов)
(Посмотреть подробную\nинформацию о посте) <.. (Посмотреть\nкомментарии) : extend
(Посмотреть подробную\nинформацию о посте) <.. (Посмотреть полное\nсодержание поста) : extend
user -left-> (Управлять постами)
(Управлять постами) <-up. (Создать\nпост) : extend
(Управлять постами) <-left. (Редактировать\nпост) : extend
(Управлять постами) <.. (Удалить\nпост) : extend
user -right-> (Взаимодействовать\nc постами)
(Комментировать) <-up. (Взаимодействовать\nc постами) : extend
(Поставить/убрать\nлайк) <-down. (Взаимодействовать\nc постами) : extend
@enduml