@startuml
"Авторизованный Пользователь" as user
user --> (Использовать настройки)
(Использовать настройки) <-left. (Изменить данные\nаккаунта)
(Использовать настройки) <.. (Настроить\nотправку уведомлений)
(Использовать настройки) <-right. (Удалить\nаккаунт)
(Использовать настройки) <.. (Выйти из\nучетной записи)
@enduml