// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Di1-aG40L7RTqe7MCgYlnYRh7W2eg5c',
    appId: '1:35889365404:web:0c18634355d9604f2b0859',
    messagingSenderId: '35889365404',
    projectId: 'blogpost-928ac',
    authDomain: 'blogpost-928ac.firebaseapp.com',
    storageBucket: 'blogpost-928ac.appspot.com',
    measurementId: 'G-X6V57RQEV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8fwbVHnG8nlVUEPkTwg-pwRRXkjh_5Lg',
    appId: '1:35889365404:android:538d49237b5f60952b0859',
    messagingSenderId: '35889365404',
    projectId: 'blogpost-928ac',
    storageBucket: 'blogpost-928ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzl_f6ijyLV2fVboy4LQrxoHip_C41roA',
    appId: '1:35889365404:ios:482f6692e053a85f2b0859',
    messagingSenderId: '35889365404',
    projectId: 'blogpost-928ac',
    storageBucket: 'blogpost-928ac.appspot.com',
    iosBundleId: 'com.example.blogpost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzl_f6ijyLV2fVboy4LQrxoHip_C41roA',
    appId: '1:35889365404:ios:5178ec6095a2454e2b0859',
    messagingSenderId: '35889365404',
    projectId: 'blogpost-928ac',
    storageBucket: 'blogpost-928ac.appspot.com',
    iosBundleId: 'com.example.blogpost.RunnerTests',
  );
}
